### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by zzf0227** [SayedNadim/SIFNet#1] opened 2023-05-05 17:40 UTC
Hi authors,

Thanks for your excellent work, well done!

When I do the training of the model, the dataset exists in the local folder and the absolute path where the dataset is located is set in the yaml file, but the following error is prompted:
===> Loading datasets
Total instance number: 11
===> Loaded datasets
Total instance number: 11
===> Loaded test datasets
Traceback (most recent call last):
  File "G:/SIFNet-main/celeb/train.py", line 291, in <module>
    train(epoch, start_step)
  File "G:/SIFNet-main/celeb/train.py", line 54, in train
    for batch in training_data_loader:
  File "D:\anaconda\Anaconda\envs\Pytorch_zzf\lib\site-packages\torch\utils\data\dataloader.py", line 517, in __next__
    data = self._next_data()
  File "D:\anaconda\Anaconda\envs\Pytorch_zzf\lib\site-packages\torch\utils\data\dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "D:\anaconda\Anaconda\envs\Pytorch_zzf\lib\site-packages\torch\utils\data\dataloader.py", line 1225, in _process_data
    data.reraise()
  File "D:\anaconda\Anaconda\envs\Pytorch_zzf\lib\site-packages\torch\_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "G:\SIFNet-main\celeb\Data\Dataloader.py", line 47, in __getitem__
    item = self.load_item(index)
  File "G:\SIFNet-main\celeb\Data\Dataloader.py", line 89, in load_item
    mask = self.load_mask(img, index)
  File "G:\SIFNet-main\celeb\Data\Dataloader.py", line 117, in load_mask
    mask = Image.open(self.mask_data[index], as_gray=True)
TypeError: open() got an unexpected keyword argument 'as_gray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\Anaconda\envs\Pytorch_zzf\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda\Anaconda\envs\Pytorch_zzf\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\Anaconda\envs\Pytorch_zzf\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\SIFNet-main\celeb\Data\Dataloader.py", line 49, in __getitem__
    raise ValueError('loading error: ' + self.samples[index])
ValueError: loading error: G:\\SIFNet-main\\Dataset\\CelebA_HQ\\train\\2.jpg
How to solve this problem?
Many thanks for your help! Look forward to your reply!

Best wishes

**Comment by SayedNadim** [comment] 2023-05-25 08:42
Hi,
Thank you for your interest in our work.
Can you please check the mask? It seems the error is coming from an error in loading the mask as gray.
Please let me know if I can help in any way. 
Thanks.

**Comment by zzf0227** [comment] 2023-05-25 15:31
>Dear author, thank you for your answer and wish you a happy and healthy life!

**Comment by SayedNadim** [comment] 2023-05-26 00:00
Hi, if the issue is resolved, can you please close it? Thanks

**Closed as completed** 2023-05-26 03:04 UTC
